version: '3.8'

services:
  dolibarr:  # ← Nombre fijo aquí
    image: tuxgasy/dolibarr:latest
    container_name: ${DOLI_CONTAINER_NAME}
    ports:
      - "${DOLI_PORT}:80"
    environment:
      DOLI_ADMIN_LOGIN: ${DOLI_ADMIN_LOGIN}
      DOLI_ADMIN_PASSWORD: ${DOLI_ADMIN_PASSWORD}
      DOLI_DB_HOST: ${DOLI_DB_HOST}
      DOLI_DB_PORT: ${DOLI_DB_PORT}
      DOLI_DB_NAME: ${DOLI_DB_NAME}
      DOLI_DB_USER: ${DOLI_DB_USER}
      DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD}
    volumes:
      - ./custom:/var/www/html/custom
      - ./documents:/var/www/html/documents
      - ./conf:/var/www/html/conf
    depends_on:
      - db  # ← nombre fijo

  db:  # ← Nombre fijo aquí también
    image: mariadb:10.5
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOLI_DB_NAME}
      MYSQL_USER: ${DOLI_DB_USER}
      MYSQL_PASSWORD: ${DOLI_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
